version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  frontend: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    ports:
        - '80:8080'
        - '49153:49153'
  backend:
    build: backend
    command: npm start
    depends_on:
            - redis
    ports:
      - "8000:8000"